### ISSUE TITLE
How to do a LAN shared pkgfile cache?

### ISSUE THREAD

**Issue by cryptarch** [falconindy/pkgfile#45] opened 2019-04-02 21:22 UTC
Hi @falconindy,

I already use a "network shared pacman cache" as described in the [pacman tips and tricks on the wiki](https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Network_shared_pacman_cache). Let's call the machine with the shared cache `A`, and the client machines `B` and `C`.

Machine `A` uses nginx to serve files from `/var/cache/pacman/pkg`. `B` and `C` have `A`'s IP address at the top of their mirrorlists. It works fine when I do `pacman -Syu`.

Since `B` and `C` use `A` for their primary mirror, when they run `pkgfile -u`, they look at `A` first, and of course get a 404 since `/var/cache/pacman/pkg/` doesn't contain the various `*.files` entries from `/var/cache/pkgfile/`.

On `A`, I've tried running `pkgfile -u -D /var/cache/pacman/pkg/`, which looks like it does what I expect:
```
$ ls -l /var/cache/pacman/pkg/*.files
-rw-r--r-- 1 root root 177416384 Apr  3 07:33 /var/cache/pacman/pkg/community.files
-rw-r--r-- 1 root root   7367500 Apr  3 07:33 /var/cache/pacman/pkg/core.files
-rw-r--r-- 1 root root  87659468 Apr  3 07:33 /var/cache/pacman/pkg/extra.files
-rw-r--r-- 1 root root    605080 Apr  3 07:33 /var/cache/pacman/pkg/multilib.files
```

But when I attempt to update pkgfile on `B` and `C` I get errors due to "invalid or incomplete multibyte or wide characters":
```
$ sudo pkgfile -u
:: Updating 3 repos...
  download complete: core                 [     7.0 MiB  37.3M/s  2 remaining]
error: failed to create archive reader for core: Invalid or incomplete multibyte or wide character
  download complete: extra                [    83.6 MiB  53.8M/s  1 remaining]
error: failed to create archive reader for extra: Invalid or incomplete multibyte or wide character
  download complete: community            [   169.2 MiB  73.1M/s  0 remaining]
:: download complete in 2.32s             <   259.8 MiB   112M/s  3 files    >
:: waiting for 1 process to finish repacking repos...
error: failed to create archive reader for community: Invalid or incomplete multibyte or wide character
```

When I check the modification times on the `B` and `C` `/var/cache/pkgfile/*.files`, I can see they have not been updated.

The nginx logs on `A` show the files were successfully accessed, and I can use Wget on `B` and `C` to manually retrieve the pkgfile `*.files` entries.

My googlings on these errors all point to something called debtap, which seems to be used by some other distro, and no good fixes in sight.

I guess a workaround could be to use the `--config=FILE` option to pkgfile and force all three of `A`, `B` and `C` to use an external mirror. That strikes me as inelegant because it will require maintaining two mirrorlists, while tripling external traffic instead of taking advantage of the LAN.

Is there something extra I need to do to make a LAN-shared pkgfile cache work properly?

Maybe nginx is encoding the files incorrectly when it serves them up? If I recall correctly, it is possible to force which file encoding nginx uses, based on file extension. If that's the answer, what encoding does pkgfile want to consume?

**Comment by falconindy** [comment] 2019-04-02 21:37
The .files DBs are compressed tarballs. You should *not* be attempting to prescribe any encoding.

If you fetch the files DBs from the server with curl/wget from B/C, do they have the same checksum as they do on A?

**Comment by cryptarch** [comment] 2019-04-02 21:49
> The .files DBs are compressed tarballs. You should not be attempting to prescribe any encoding.

Okay, that works for me :)

> If you fetch the files DBs from the server with curl/wget from B/C, do they have the same checksum as they do on A?

Yeah, it looks to be the same. Using `extra.files` as an example:

```
A $ md5sum /var/cache/pacman/pkg/extra.files
10899b2ed74bce5e3b559c839288839b  /var/cache/pacman/pkg/extra.files
```

```
B $ wget -q A:8080/extra.files
B $ md5sum extra.files
10899b2ed74bce5e3b559c839288839b  extra.files
```

**Comment by falconindy** [comment] 2019-04-03 20:01
Not really sure why you're seeing this. In practice, you have an http server which theoretically isn't very different from a remote http server. It's conceviable, but seems unlikely that the local-ness of the server exposes some sort of bug/race in pkgfile's downloader. I recall some bugs in this area, but re-testing this with `Server = /var/lib/pacman/sync` and running `pkgfile -uu` doesn't show any similar problem as to what you're seeing.

You might enable CURLOPT_VERBOSE for the easy handles in src/update.c and see if anything useful is logged.

**Comment by cryptarch** [comment] 2019-04-03 20:47
Hi @falconindy 

I tried adding `curl_easy_setopt(repo->curl, CURLOPT_VERBOSE, 1L);` in with the other CURLOPTs in `download_queue_request`. I don't see anything useful, but the verbose output is attached if you want to have a look.

[pkgfile.log](https://github.com/falconindy/pkgfile/files/3040660/pkgfile.log)

**Comment by falconindy** [comment] 2019-04-07 15:56
So, I'm still having trouble reproducing this between my machine (running nginx, hosting the .files DBs from /var/lib/pacman/sync) and a VM pointed back at the host.

Is it possble you're trying to share /var/cache/pkgfile? You can't do that, since the DBs that pkgfile uses aren't the same as pacman's.

If the above isn't true, could you please pare down your nginx config to the basics to debug further?

**Comment by cryptarch** [comment] 2019-04-07 20:05
Yeah, not trying to share `/var/cache/pkgfile`. In any case, that would cause problems with my pacman updates, but pacman is working fine with this setup.

Here is a minimal nginx config which reproduces the problem:
```
user http;
daemon off;
error_log /var/log/nginx/error.log warn;
events {
    worker_connections 1024;
}
http {
    server {
        listen 8080;
        root /var/cache/pacman/pkg;
        server_name A;
        try_files $uri $uri/ =404;
    }
}
```

(Although I usually compile nginx with my own preferred settings, the problem persists when using `extra/nginx` from the Arch Linux repos.)

**Comment by falconindy** [comment] 2019-04-07 20:11
`/var/cache/pacman/pkg`? Was that meant to be `/var/lib/pacman/sync`?

**Comment by cryptarch** [comment] 2019-04-07 20:18
I have the db files from `/var/lib/pacman/sync` symlinked into `/var/cache/pacman/pkg`. That way when the client requests a particular package, nginx can find it and serve it up.

This follows the instructions at [the wiki](https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Read-only_cache).

My `/var/cache/pacman/pkg/` directory has all these:
```
$ ls -l /var/cache/pacman/pkg/*.files /var/cache/pacman/pkg/*.db
lrwxrwxrwx 1 root root        33 Oct 15 07:16 /var/cache/pacman/pkg/community.db -> /var/lib/pacman/sync/community.db
-rw-r--r-- 1 root root 177416384 Apr  3 07:33 /var/cache/pacman/pkg/community.files
lrwxrwxrwx 1 root root        28 Oct 15 07:16 /var/cache/pacman/pkg/core.db -> /var/lib/pacman/sync/core.db
-rw-r--r-- 1 root root   7367500 Apr  3 07:33 /var/cache/pacman/pkg/core.files
lrwxrwxrwx 1 root root        29 Oct 15 07:16 /var/cache/pacman/pkg/extra.db -> /var/lib/pacman/sync/extra.db
-rw-r--r-- 1 root root  87659468 Apr  3 07:33 /var/cache/pacman/pkg/extra.files
-rw-r--r-- 1 root root    605080 Apr  3 07:33 /var/cache/pacman/pkg/multilib.files
```

**Comment by falconindy** [comment] 2019-04-07 21:29
*shrug* basic nginx config you posted still works for me between host and VM.

What locale is this on the affected client side?

**Comment by cryptarch** [comment] 2019-04-07 21:49
> What locale is this on the affected client side?

I'm in Australia:

```
B $ cat /etc/locale.conf
LANG=en_AU.UTF-8
```

```
B $ grep -v "^#" /etc/locale.gen
en_AU.UTF-8 UTF-8
en_AU ISO-8859-1
en_GB.UTF-8 UTF-8
en_GB ISO-8859-1
en_US.UTF-8 UTF-8
en_US ISO-8859-1
```

```
B $ sudo env | grep LC
LC_ALL=en_AU.UTF-8
```

**Comment by falconindy** [comment] 2019-10-13 15:09
I'm closing this because I'm quite sure this is a local configuration problem, and not actually a bug in pkgfile.

Feel free to reopen if you have evidence to the contrary.

**Closed by falconindy** 2019-10-13 15:09 UTC

**Comment by falconindy** [comment] 2019-10-15 12:23
One thing that occurs to me is that you might get this error if you're trying to fetch pkgfile DBs from the remote machine directly. pacman ".files" are tar formatted, pkgfile ".files" are cpio formatted. It's probably unfortunate that I chose to keep the file extension for a differently formatted file.

**Comment by cryptarch** [comment] 2019-10-15 21:08
This is no longer really affecting me since I've been transitioning everything to Void Linux. Thanks anyway for the follow up and keep up the good work :)
